name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pypa/setuptools
      run: python -m pip install wheel

    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Determine new release version
      id: release-version
      if: github.ref == 'refs/heads/main'
      run: |
        current_version=${{ steps.tag.outputs.TAG_NAME }}
        IFS='.' read -ra version_parts <<< "$current_version"
        new_version="${version_parts[0]}.${version_parts[1]}.$((${version_parts[2]} + 1))"
        echo "::set-output name=NEW_RELEASE_VERSION::$new_version"

    - name: Update version in setup.py
      run: |
        if [[ -n "${{ steps.release-version.outputs.NEW_RELEASE_VERSION }}" ]]; then
          new_release_version="${{ steps.release-version.outputs.NEW_RELEASE_VERSION }}"
          sed -i "s/{{VERSION_PLACEHOLDER}}/${new_release_version}/g" setup.py
        else
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py
        fi

    - name: Build a binary wheel
      run: python setup.py sdist bdist_wheel

    - name: Publish package 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Adjust release tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -d "${{ steps.tag.outputs.TAG_NAME }}"
        git push origin :refs/tags/${{ steps.tag.outputs.TAG_NAME }}
        git tag "${{ steps.tag.outputs.TAG_NAME }}"
        git push origin "${{ steps.tag.outputs.TAG_NAME }}"

